default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: export_report_with_rake_sample/dev

test:
  <<: *default
  database: export_report_with_rake_sample/test

production:
  <<: *default
  database: export_report_with_rake_sample/prod
